### ISSUE TITLE
Not find ''SparseCollationWithClusterinfo'' in data_utils.collations.py

### ISSUE THREAD

**Issue by chenhaomingbob** [YanhaoWu/CVPR2023_STSSL#4]
你好。
在按照train_stssl.py运行后，会执行到trakc_model.py，但发现`SparseSegmentWithTrackCollation`这个类是缺失的，[SparseSegmentWithTrackCollation](https://github.com/YanhaoWu/STSSL/blob/529d0e5134920778258d22353e828af45d557de2/data_preprocessing/track_model.py#L5)

您能帮忙看看吗？

**Comment by YanhaoWu** [comment]
不好意思，可能是版本迭代问题改名了，我现在重新加进去了，您看看 : )
